#!/usr/bin/env bash
# Installing Nginx where should be listening on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
