#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend layoub.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 433645-web-01 100.26.161.4:80
        server 433645-web-02 52.86.2.31:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
