#!/usr/bin/env bash
# Configuration of a server to listening on port 80
# Nginx runs and listens on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
