#!/usr/bin/env bash
# Configuration of a server to listening on port 80
# Nginx runs and listens on port 80 of all the server’s active IPv4 IPs
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
