#!/usr/bin/env bash
# The program indefinitely writes "I am alive" to the file /tmp/my_process
# The program pauses two seconds in between each message

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
