#!/usr/bin/env bash
# The program displays numbers from 1 to 20 in addition to:
# A "bad luck from China" for the fourth iteration
# A"bad luck from Japan" for the ninth iteration
# A "bad luck from Italy" for the seventeenth loop iteration

count=1
while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
