#!/usr/bin/env bash
# The program displays the content of the current directory in list-format
# Only display the part of the name after the first dash is displayed

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
